/* Create Tables */

CREATE TABLE NEURON
(
	ID serial NOT NULL,
	TITLE varchar NOT NULL,
	CONTENT text,
	NEURON_LEVEL int NOT NULL,
	LEFT_EDGE float NOT NULL UNIQUE,
	RIGHT_EDGE float NOT NULL UNIQUE,
	CREATE_DATE date NOT NULL,
	UPDATE_DATE date NOT NULL,
	PRIMARY KEY (id)
) WITHOUT OIDS;